2018-12-18 Tuesday 10:08:17  sylogger.py : ERROR  list index out of range
